### ISSUE TITLE
PhantomJS and Selenium not working when trying to find elelement

### ISSUE THREAD

**Issue by karunkrishna** [karunkrishna/aws_linux_algo_setup#1]
Total elapsed time for fetching Zacks Earnings and Divident Dates: 5.059575
Begin fetching Top Option page....
Traceback (most recent call last):
  File "barchart_unusual_activity.py", line 656, in <module>
    main_table_element = WebDriverWait(driver, 60).until(EC.presence_of_element_located((By.CLASS_NAME, 'bc-table-scrollable-inner')))
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Screenshot: available via screen

Exception ignored in: <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x7ff5c7735780>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/xlsxwriter/workbook.py", line 153, in __del__
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
ubuntu@ip-172-31-44-131:~/WebScraper/barchart$

**Comment by karunkrishna** [comment]
Switched over to chrome browser
